[package]
name = "Day1"
version = "0.1.0"
authors = ["Rachel Thornton <rachelmthornton18@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queue = "0.3.1"